/**
 * @File Name          : NotYetImplementedException.cls
 * @Description        : 
 * @Author             : Seth Boyd
 * @Group              : 
 * @Last Modified By   : Seth Boyd
 * @Last Modified On   : 4/25/2019, 10:03:26 AM
 * @Modification Log   : 
 *==============================================================================
 * Ver         Date                     Author      		      Modification
 *==============================================================================
 * 1.0    4/25/2019, 10:03:26 AM   Seth Boyd     Initial Version
**/
public class NotYetImplementedException extends Exception{
}